auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: debug

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  replication_factor: 1

  ring:
    kvstore:
      store: memberlist

  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

memberlist:
  join_members: []
  bind_addr:
    - 0.0.0.0
  bind_port: 7946

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

pattern_ingester:
  enabled: true
  metric_aggregation:
    loki_address: 127.0.0.1:3100

limits_config:
  metric_aggregation_enabled: true

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

ruler:
  alertmanager_url: http://localhost:9093

frontend:
  encoding: protobuf

analytics:
  reporting_enabled: false
